# Generated by Django 3.1 on 2020-09-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TO_DO_ITEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_team', models.CharField(choices=[('IT-POSTPAID', 'IT-Postpaid'), ('IT-PREPAID', 'IT-Prepaid'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('RA', 'RA')], default='IT-POSTPAID', max_length=50)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('WORKING', 'Working'), ('TRANSFERED', 'Transfered'), ('DONE', 'Done'), ('Suspended', 'SUSPENDED'), ('WAITING', 'Waiting')], default='STARTED', max_length=30)),
                ('source', models.CharField(choices=[('IT', 'it'), ('SHOPS', 'Shops'), ('RA', 'ra'), ('FINANCE', 'Finance'), ('OFFICE', 'Office')], default='IT', max_length=30)),
                ('assigned_to', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
